name: Build PDF Slides

on:
  push:
    paths:
      - 'slides/**'

jobs:
  build-slides:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Marp
        run: npm install -g @marp-team/marp-cli
      - name: Generate PDFs
        run: |
          mkdir -p pdf_slides
          find slides -name "*.md" -print0 | xargs -0 -I{} marp "{}" -o "pdf_slides/$(basename {} .md).pdf"
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: slides-pdf
          path: pdf_slides/
